### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by yoni** [jm/we_the_people#2]
I'm trying to get this building on my OS X box. My first step is to add all development dependencies to the gemspec and be able to run rake test. Unfortunately, it's not been easy.

It seems that `rcov` doesn't work with Ruby 1.9, which implies that you must be using 1.8. When I switch to 1.8 (using `rvm`), I can't run things for other reasons. Basically, I'm in Ruby dependency hell. :)

Are you planning on supporting only Ruby 1.8? If that's the case, you might consider upgrading to 1.9, instead. I'll keep trying to get 1.8 working, in the meanwhile.

**Comment by jm** [comment]
Yeah I base all my gems on [RakeGem](http://github.com/mojombo/rakegem) but it has some 1.8 cruft I need to clean out.  I'll try to do that tomorrow and close this issue when I do.

**Comment by yoni** [comment]
Word. I haven't used RakeGem, but now that all makes sense.

Also, I'm not blocked on _using_ the gem, just on building some of the tasks, so it's all good.

**Comment by jm** [comment]
:fire: :skull: to rcov in dbbb16d
